---
title: "Getting Started"
date: 2018-05-02T00:00:00+00:00
anchor: "getting-started"
weight: 20
---

= Getting Started
:sectlinks:
:docker: https://www.docker.com/
:repo: https://github.com/owncloud/ocis-hello/tree/master/config
:prom: https://prometheus.io/

== Installation

So far, we are offering two different variants for the installation.
You can choose between {docker}[Docker] or pre-built binaries which are stored on our download mirrors and GitHub releases.
In future, we may also provide system packages for the major distributions, if we see the need for it.

=== Docker

TBD

=== Binaries

TBD

== Configuration

Configuration options can be provide via xref:environment-variables[environment variables] and xref:command-line-flags[command-line flags].
Both of these approaches split values up into global values and command-specific.

=== Environment Variables

==== Global

HELLO_LOG_LEVEL:: Set logging level, defaults to `info`

HELLO_LOG_COLOR:: Enable colored logging, defaults to `true`

HELLO_LOG_PRETTY:: Enable pretty logging, defaults to `true`

==== Server

HELLO_DEBUG_ADDR:: Address to bind debug server, defaults to `0.0.0.0:8390`

HELLO_DEBUG_TOKEN:: Token to grant metrics access, empty default value

HELLO_DEBUG_PPROF:: Enable pprof debugging, defaults to `false`

HELLO_HTTP_ADDR:: Address to bind http server, defaults to `0.0.0.0:8380`

HELLO_HTTP_ROOT:: Root path for http endpoint, defaults to `/`

HELLO_ASSET_PATH:: Path to custom assets, empty default value

==== Health

HELLO_DEBUG_ADDR:: Address to debug endpoint, defaults to `0.0.0.0:8390`

=== Command Line Flags

==== Global

--log-level:: Set logging level, defaults to `info`

--log-color:: Enable colored logging, defaults to `true`

--log-pretty:: Enable pretty logging, defaults to `true`

==== Server

--debug-addr:: Address to bind debug server, defaults to `0.0.0.0:8390`

--debug-token:: Token to grant metrics access, empty default value

--debug-pprof:: Enable pprof debugging, defaults to `false`

--http-addr:: Address to bind http server, defaults to `0.0.0.0:8380`

--http-root:: Root path for http endpoint, defaults to `/`

--asset-path:: Path to custom assets, empty default value

==== Health

--debug-addr:: Address to debug endpoint, defaults to `0.0.0.0:8390`

=== Configuration File

The project configuration file can be written in either `JSON` or `YAML`.
Take a look at {repo}[our repository] for a complete configuration example.

Configuration files located in `/etc/ocis/hello.yml`, `+${HOME}/.ocis/hello.yml+` or `$(pwd)/config/hello.yml` are automatically loaded.

== Usage

The program provides a few sub-commands on execution.
The available configuration methods have already been mentioned above.

You can always see a formatted help output if you execute the binary via `ocis-hello --help`.

=== Server

The server command starts the HTTP and debug servers on two addresses within a single process.

The HTTP server serves the general web service while the debug server is used for the health check, readiness check, and to serve the metrics mentioned below.

For further help, please execute the following command:

[source,console]
----
ocis-hello server --help
----

Currently, it outputs the following:

[source,console]
----
Start integrated server

Usage:
  ocis-hello server [flags]

Flags:
      --asset-path string    Path to custom assets
      --debug-addr string    Address to bind debug server
      --debug-pprof          Enable pprof debugging
      --debug-token string   Token to grant metrics access
  -h, --help                 help for server
      --http-addr string     Address to bind http server
      --http-root string     Root path for http endpoint

Global Flags:
      --log-color          Enable colored logging
      --log-level string   Set logging level
      --log-pretty         Enable pretty logging
----

=== Health

The health command executes a health check.
If the exit code equals zero, the service should be up and running.
If the exit code is greater than zero, the service is not in a healthy state.
This command is used within our Docker containers; it is also usable within Kubernetes.

[source,console]
----
ocis-hello health --help
----

Currently, it outputs the following:

[source,console]
----
Check health status

Usage:
  ocis-hello health [flags]

Flags:
      --debug-addr string   Address to debug endpoint
  -h, --help                help for health

Global Flags:
      --log-color          Enable colored logging
      --log-level string   Set logging level
      --log-pretty         Enable pretty logging
----

== Metrics

The service provides {prom}[Prometheus] metrics through the debug endpoint.

You can, optionally, secure the metrics endpoint by using a random token.
The random token must be configured either through the `--debug-token` flag, or the environment variable `HELLO_DEBUG_TOKEN`, which is mentioned above.

By default, the metrics endpoint is bound to `+http://0.0.0.0:8390/metrics+`.

go_gc_duration_seconds:: A summary of the GC invocation durations

go_gc_duration_seconds_sum:: A summary of the GC invocation durations

go_gc_duration_seconds_count:: A summary of the GC invocation durations

go_goroutines:: The number of goroutines that currently exist

go_info:: Information about the Go environment

go_memstats_alloc_bytes:: The number of bytes allocated and still in use

go_memstats_alloc_bytes_total:: The total number of bytes allocated, even if freed

go_memstats_buck_hash_sys_bytes:: The number of bytes used by the profiling bucket hash table

go_memstats_frees_total:: The total number of frees

go_memstats_gc_cpu_fraction:: The fraction of this program's available CPU time used by the GC since the program started

go_memstats_gc_sys_bytes:: The number of bytes used for garbage collection system metadata

go_memstats_heap_alloc_bytes:: The number of heap bytes allocated and still in use

go_memstats_heap_idle_bytes:: The number of heap bytes waiting to be used

go_memstats_heap_inuse_bytes:: The number of heap bytes that are in use

go_memstats_heap_objects:: The number of allocated objects

go_memstats_heap_released_bytes:: The number of heap bytes released to OS

go_memstats_heap_sys_bytes:: The number of heap bytes obtained from system

go_memstats_last_gc_time_seconds:: The number of seconds since 1970 of last garbage collection

go_memstats_lookups_total:: The total number of pointer lookups

go_memstats_mallocs_total:: The total number of mallocs

go_memstats_mcache_inuse_bytes:: The number of bytes in use by mcache structures

go_memstats_mcache_sys_bytes:: The number of bytes used for mcache structures obtained from system

go_memstats_mspan_inuse_bytes:: The number of bytes in use by mspan structures

go_memstats_mspan_sys_bytes:: The number of bytes used for mspan structures obtained from system

go_memstats_next_gc_bytes:: The number of heap bytes when next garbage collection will take place

go_memstats_other_sys_bytes:: The number of bytes used for other system allocations

go_memstats_stack_inuse_bytes:: The number of bytes in use by the stack allocator

go_memstats_stack_sys_bytes:: The number of bytes obtained from system for stack allocator

go_memstats_sys_bytes:: The number of bytes obtained from system

go_threads:: The number of OS threads created

promhttp_metric_handler_requests_in_flight:: The current number of scrapes being served

promhttp_metric_handler_requests_total:: The total number of scrapes by HTTP status code
