// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v0alpha1/hello.proto

package v0alpha1api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GreetRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetRequest) Reset()         { *m = GreetRequest{} }
func (m *GreetRequest) String() string { return proto.CompactTextString(m) }
func (*GreetRequest) ProtoMessage()    {}
func (*GreetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_92f8facb0529762c, []int{0}
}

func (m *GreetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetRequest.Unmarshal(m, b)
}
func (m *GreetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetRequest.Marshal(b, m, deterministic)
}
func (m *GreetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetRequest.Merge(m, src)
}
func (m *GreetRequest) XXX_Size() int {
	return xxx_messageInfo_GreetRequest.Size(m)
}
func (m *GreetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GreetRequest proto.InternalMessageInfo

func (m *GreetRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GreetResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetResponse) Reset()         { *m = GreetResponse{} }
func (m *GreetResponse) String() string { return proto.CompactTextString(m) }
func (*GreetResponse) ProtoMessage()    {}
func (*GreetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_92f8facb0529762c, []int{1}
}

func (m *GreetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetResponse.Unmarshal(m, b)
}
func (m *GreetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetResponse.Marshal(b, m, deterministic)
}
func (m *GreetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetResponse.Merge(m, src)
}
func (m *GreetResponse) XXX_Size() int {
	return xxx_messageInfo_GreetResponse.Size(m)
}
func (m *GreetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GreetResponse proto.InternalMessageInfo

func (m *GreetResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GreetResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*GreetRequest)(nil), "ocis.hello.v0alpha1.GreetRequest")
	proto.RegisterType((*GreetResponse)(nil), "ocis.hello.v0alpha1.GreetResponse")
}

func init() { proto.RegisterFile("v0alpha1/hello.proto", fileDescriptor_92f8facb0529762c) }

var fileDescriptor_92f8facb0529762c = []byte{
	// 399 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x31, 0x6f, 0xd4, 0x30,
	0x14, 0x80, 0x95, 0x94, 0x82, 0x30, 0xad, 0x74, 0x72, 0x3b, 0x44, 0x11, 0x42, 0x47, 0x06, 0x84,
	0x4e, 0x24, 0xbe, 0x86, 0x2d, 0x2c, 0x94, 0x52, 0xf5, 0x90, 0x28, 0x43, 0xbb, 0xb1, 0x39, 0xe1,
	0xc9, 0x31, 0x72, 0xfc, 0x8c, 0xed, 0xdc, 0x6d, 0x0c, 0xcc, 0x4c, 0x30, 0x33, 0xf2, 0x8b, 0xf8,
	0x0b, 0xfc, 0x10, 0x14, 0x5f, 0x73, 0x9c, 0x74, 0x08, 0x75, 0xca, 0xcb, 0xf3, 0xe7, 0xe7, 0xef,
	0x3d, 0x9b, 0x1c, 0x2f, 0xe7, 0x5c, 0x99, 0x96, 0x9f, 0xb0, 0x16, 0x94, 0xc2, 0xc2, 0x58, 0xf4,
	0x48, 0x8f, 0xb0, 0x91, 0xae, 0x58, 0x67, 0x46, 0x20, 0x7d, 0x28, 0x10, 0x85, 0x02, 0xc6, 0x8d,
	0x64, 0x5c, 0x6b, 0xf4, 0xdc, 0x4b, 0xd4, 0x6e, 0xbd, 0x25, 0x7d, 0x16, 0x3e, 0x4d, 0x2e, 0x40,
	0xe7, 0x6e, 0xc5, 0x85, 0x00, 0xcb, 0xd0, 0x04, 0x62, 0x97, 0xce, 0x32, 0x72, 0x70, 0x61, 0x01,
	0xfc, 0x15, 0x7c, 0xea, 0xc1, 0x79, 0x4a, 0xc9, 0x1d, 0xcd, 0x3b, 0x48, 0xa2, 0x69, 0xf4, 0xf4,
	0xfe, 0x55, 0x88, 0xb3, 0x17, 0xe4, 0xf0, 0x86, 0x71, 0x06, 0xb5, 0x03, 0x9a, 0x90, 0x7b, 0x1d,
	0x38, 0xc7, 0xc5, 0xc8, 0x8d, 0xbf, 0x74, 0x42, 0xf6, 0xc0, 0xda, 0x24, 0x0e, 0xd9, 0x21, 0x2c,
	0x3f, 0x93, 0x83, 0xc5, 0xa0, 0x7f, 0x0d, 0x76, 0x29, 0x1b, 0xa0, 0x9a, 0xec, 0x87, 0x62, 0xf4,
	0x71, 0xf1, 0x8f, 0xde, 0x8a, 0x6d, 0x99, 0x34, 0xfb, 0x1f, 0xb2, 0x76, 0xc9, 0x1e, 0x7d, 0xf9,
	0xf5, 0xfb, 0x7b, 0x9c, 0x64, 0x47, 0x61, 0x1c, 0x9b, 0x21, 0x8a, 0x01, 0xaa, 0xa2, 0xd9, 0xab,
	0x1f, 0xf1, 0xb7, 0xd3, 0xaf, 0x31, 0xfd, 0x19, 0x91, 0xfd, 0xe0, 0x91, 0x5d, 0x92, 0x43, 0x5c,
	0xe9, 0x33, 0x85, 0xfd, 0x87, 0xe9, 0x45, 0x57, 0x2f, 0xe8, 0x93, 0xd6, 0x7b, 0xe3, 0x2a, 0xc6,
	0x84, 0xf4, 0x6d, 0x5f, 0x17, 0x0d, 0x76, 0x0c, 0x57, 0xba, 0x19, 0x08, 0x36, 0x08, 0xe4, 0x41,
	0x20, 0x3d, 0x76, 0xbd, 0x31, 0x68, 0xfd, 0xcb, 0x71, 0x71, 0x20, 0x67, 0x0b, 0x42, 0x4e, 0x0d,
	0x6f, 0x5a, 0xc8, 0xcb, 0x62, 0x4e, 0xab, 0xdb, 0xd5, 0x62, 0xb5, 0xc2, 0x9a, 0x75, 0xdc, 0x79,
	0xb0, 0xec, 0xed, 0x9b, 0xb3, 0xf3, 0x77, 0xd7, 0xe7, 0xe5, 0xde, 0x49, 0x31, 0x9f, 0xc5, 0x51,
	0x5c, 0x4e, 0xb8, 0x31, 0x4a, 0x36, 0xe1, 0x9e, 0xd8, 0x47, 0x87, 0xba, 0xda, 0xc9, 0xd8, 0x8a,
	0x4c, 0x5e, 0xc3, 0x12, 0x14, 0x1a, 0xb0, 0xd3, 0x4b, 0xae, 0x7b, 0xae, 0xfe, 0x36, 0xb2, 0x11,
	0xbc, 0xb1, 0x90, 0xb8, 0x7d, 0xf6, 0xfb, 0x07, 0xe3, 0x94, 0xb8, 0x91, 0xf5, 0xdd, 0xf0, 0x0e,
	0x9e, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0x38, 0xf6, 0xfd, 0xe0, 0x80, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HelloServiceClient is the client API for HelloService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HelloServiceClient interface {
	Greet(ctx context.Context, in *GreetRequest, opts ...grpc.CallOption) (*GreetResponse, error)
}

type helloServiceClient struct {
	cc *grpc.ClientConn
}

func NewHelloServiceClient(cc *grpc.ClientConn) HelloServiceClient {
	return &helloServiceClient{cc}
}

func (c *helloServiceClient) Greet(ctx context.Context, in *GreetRequest, opts ...grpc.CallOption) (*GreetResponse, error) {
	out := new(GreetResponse)
	err := c.cc.Invoke(ctx, "/ocis.hello.v0alpha1.HelloService/Greet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloServiceServer is the server API for HelloService service.
type HelloServiceServer interface {
	Greet(context.Context, *GreetRequest) (*GreetResponse, error)
}

// UnimplementedHelloServiceServer can be embedded to have forward compatible implementations.
type UnimplementedHelloServiceServer struct {
}

func (*UnimplementedHelloServiceServer) Greet(ctx context.Context, req *GreetRequest) (*GreetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Greet not implemented")
}

func RegisterHelloServiceServer(s *grpc.Server, srv HelloServiceServer) {
	s.RegisterService(&_HelloService_serviceDesc, srv)
}

func _HelloService_Greet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GreetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServiceServer).Greet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ocis.hello.v0alpha1.HelloService/Greet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServiceServer).Greet(ctx, req.(*GreetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HelloService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ocis.hello.v0alpha1.HelloService",
	HandlerType: (*HelloServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Greet",
			Handler:    _HelloService_Greet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v0alpha1/hello.proto",
}
